### ISSUE TITLE
Visiting localhost/api via browser causes threads to panic.

### ISSUE THREAD

**Issue by jasonlor** [fairingrey/actix-realworld-example-app#12]
Just downloaded/set it up to try it out.
Any idea what's causing this?

thread 'arbiter:ed63170e-3426-4aaa-bbb5-2ccfbfb2147a:actix-net-worker-3' panicked at 'Failed to create pool.: InternalServerError', src/libcore/result.rs:997:5
thread 'arbiter:4c9e2b97-7110-42c1-8fe1-abb61979e105:actix-net-worker-4' panicked at 'Failed to create pool.: InternalServerError', src/libcore/result.rs:997:5
thread 'arbiter:c3b18044-efe3-49da-8978-3af67764e026:actix-net-worker-11' panicked at 'Failed to create pool.: InternalServerError', src/libcore/result.rs:997:5
thread 'arbiter:d4df4aae-37c6-4a75-af6e-c3426a11fb78:actix-net-worker-8' panicked at 'Failed to create pool.: InternalServerError', src/libcore/result.rs:997:5
thread 'arbiter:7f6bb722-363b-40cd-8788-bc02f2806eee:actix-net-worker-9' panicked at 'Failed to create pool.: InternalServerError', src/libcore/result.rs:997:5
thread 'arbiter:aa2b968a-40f0-4d85-8ace-7653ba749b29:actix-net-worker-7' panicked at 'Failed to create pool.: InternalServerError', src/libcore/result.rs:997:5
thread 'arbiter:96bb52d2-f4f1-46bb-857c-2a5ee7949153:actix-net-worker-2' panicked at 'Failed to create pool.: InternalServerError', src/libcore/result.rs:997:5
thread 'arbiter:882e27d2-d090-4ab0-9b78-e5f76497d71f:actix-net-worker-10' panicked at 'Failed to create pool.: InternalServerError', src/libcore/result.rs:997:5

**Comment by fairingrey** [comment]
@jasonlor 	Sorry for the late response as I don't watch this repo often (you'll have to mention me for a quicker response).

I'm not sure, actually... From what it looks like, you're trying to start up the worker threadpool for Actix-web but it's failing to create anything. What machine are you running this on? Are permissions limited?

**Comment by Light-Wizzard** [comment]
I reproduced this error, to make it go away you need to ensure the database and user is set up in PostgreSQL.

A better error handler for this type of error would help.

**Comment by pengw00** [comment]
do I need to launch postgres database?

**Comment by 0x0c72** [comment]
> do I need to launch postgres database?

it needs to be running where diesel can find it with the DATABASE_URL environment variable
